name: data_persistence
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.2

dependencies:
  core:
    path: ../core
  hive: ^2.2.3
  path_provider: ^2.1.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0
