name: data_persistence
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.2

dependencies:
  core:
    path: ../core
  path_provider: ^2.1.5
  hive: ^2.2.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
